---

- name: WildFly | Install
  include: install.yml
  tags:
    - wildfly_install

- name: WildFly | Configure
  include: config.yml
  tags:
    - wildfly_configure

- name: WildFly | Service
  include: service.yml
  tags:
    - wildfly_service

- name: WildFly | Users
  include: users.yml
  tags:
    - wildfly_users

- name: WildFly | Deploy
  include: deploy.yml
  tags:
    - wildfly_deploy
