---
wildfly_version: "10.1.0.Final"

wildfly_port: 8080

wildfly_user: wildfly
wildfly_user_home: /home/wildfly
wildfly_group: wildfly
wildfly_user_shell: /bin/sh
wildfly_user_uid: 1005

wildfly_log_file_path: "/var/log/wildfly"
wildfly_log_file_name: wildfly.log

wildfly_management_users:
  - name: admin
    password: admin

wildfly_download_wars: true

## JAVA
java_jdk_vendor: openjdk
